NLMech: rw::writer::VtkWriterInterface Class Reference
rw::writer::VtkWriterInterface Class Reference
A interface class writing data using vtk writer.
#include <writer.h>
Public Member Functions
VtkWriterInterface ()
Constructor.
VtkWriterInterface (const std::string &filename, const std::string &compress_type="")
Constructor.
~VtkWriterInterface ()
Destructor.
void open (const std::string &filename, const std::string &compress_type="")
Open a .vtu file.
void close ()
Closes the file and store it to the hard disk.
Mesh data
void appendNodes (const std::vector< util::Point3 > *nodes)
Writes the nodes to the file.
void appendNodes (const std::vector< util::Point3 > *nodes, const std::vector< util::Point3 > *u)
Writes the nodes to the file.
void appendMesh (const std::vector< util::Point3 > *nodes, const size_t &element_type, const std::vector< size_t > *en_con, const std::vector< util::Point3 > *u)
Writes the mesh data to file.
Point data
void appendPointData (const std::string &name, const std::vector< uint8_t > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< size_t > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< int > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< float > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< double > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< util::Point3 > *data)
Writes the vector point data to the file.
void appendPointData (const std::string &name, const std::vector< util::SymMatrix3 > *data)
Writes the symmetric matrix data associated to nodes to the file.
Cell data
void appendCellData (const std::string &name, const std::vector< float > *data)
Writes the float data associated to cells to the file.
void appendCellData (const std::string &name, const std::vector< util::SymMatrix3 > *data)
Writes the symmetric matrix data associated to cells to the file.
Field data
void appendFieldData (const std::string &name, const double &data)
Writes the scalar field data to the file.
void appendFieldData (const std::string &name, const float &data)
Writes the scalar field data to the file.
void addTimeStep (const double &timestep)
Writes the time step to the file.
Private Attributes
rw::writer::VtkWriter * d_vtkWriter_p
Pointer to the vtk writer class.
Detailed Description
A interface class writing data using vtk writer.
This interface separates the caller from vtk library.
Constructor & Destructor Documentation
VtkWriterInterface()
rw::writer::VtkWriterInterface::VtkWriterInterface (const std::string & filename, const std::string & compress_type = "")
Constructor.
Creates and opens .vtu file of name given by filename. The file remains open till the close() function is invoked or if the instance of this class is destroyed.
Parameters
filename Name of file which will be created
compress_type Specify the compression type (optional)
Member Function Documentation
addTimeStep()
void rw::writer::VtkWriterInterface::addTimeStep (const double & timestep)
Writes the time step to the file.
Parameters
timestep Current time step of the simulation
appendCellData() [1/2]
void rw::writer::VtkWriterInterface::appendCellData (const std::string & name, const std::vector< float > * data)
Writes the float data associated to cells to the file.
Parameters
name Name of the data
data Vector containing the data
Referenced by tools::pp::Compute::computeStrain().
appendCellData() [2/2]
void rw::writer::VtkWriterInterface::appendCellData (const std::string & name, const std::vector< util::SymMatrix3 > * data)
Writes the symmetric matrix data associated to cells to the file.
Parameters
name Name of the data
data Vector containing the data
appendFieldData() [1/2]
void rw::writer::VtkWriterInterface::appendFieldData (const std::string & name, const double & data)
Writes the scalar field data to the file.
Parameters
name Name of the data
data Value
appendFieldData() [2/2]
void rw::writer::VtkWriterInterface::appendFieldData (const std::string & name, const float & data)
Writes the scalar field data to the file.
Parameters
name Name of the data
data Value
appendMesh()
void rw::writer::VtkWriterInterface::appendMesh (const std::vector< util::Point3 > * nodes, const size_t & element_type, const std::vector< size_t > * en_con, const std::vector< util::Point3 > * u)
Writes the mesh data to file.
Parameters
nodes Vector of nodal coordinates
element_type Type of element
en_con Vector of element-node connectivity
u Vector of nodal displacement
Referenced by tools::pp::Compute::initWriter().
appendNodes() [1/2]
void rw::writer::VtkWriterInterface::appendNodes (const std::vector< util::Point3 > * nodes)
Writes the nodes to the file.
Parameters
nodes Current positions of the nodes
Referenced by tools::pp::Compute::initWriter().
appendNodes() [2/2]
void rw::writer::VtkWriterInterface::appendNodes (const std::vector< util::Point3 > * nodes, const std::vector< util::Point3 > * u)
Writes the nodes to the file.
Parameters
nodes Reference positions of the nodes
u Nodal displacements
appendPointData() [1/7]
void rw::writer::VtkWriterInterface::appendPointData (const std::string & name, const std::vector< uint8_t > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
Referenced by tools::pp::Compute::computeDamage(), tools::pp::Compute::transformU(), and tools::pp::Compute::transformV().
appendPointData() [2/7]
void rw::writer::VtkWriterInterface::appendPointData (const std::string & name, const std::vector< size_t > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [3/7]
void rw::writer::VtkWriterInterface::appendPointData (const std::string & name, const std::vector< int > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [4/7]
void rw::writer::VtkWriterInterface::appendPointData (const std::string & name, const std::vector< float > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [5/7]
void rw::writer::VtkWriterInterface::appendPointData (const std::string & name, const std::vector< double > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [6/7]
void rw::writer::VtkWriterInterface::appendPointData (const std::string & name, const std::vector< util::Point3 > * data)
Writes the vector point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [7/7]
void rw::writer::VtkWriterInterface::appendPointData (const std::string & name, const std::vector< util::SymMatrix3 > * data)
Writes the symmetric matrix data associated to nodes to the file.
Parameters
name Name of the data
data Vector containing the data
open()
void rw::writer::VtkWriterInterface::open (const std::string & filename, const std::string & compress_type = "")
Open a .vtu file.
Parameters
filename Name of file which will be created
compress_type Compression type (optional)
Referenced by tools::pp::Compute::initWriter().
The documentation for this class was generated from the following files:
/home/diehlpk/git/NLMech/src/rw/writer.h
/home/diehlpk/git/NLMech/src/rw/writer.cpp