NLMech: util::geometry Namespace Reference
util::geometry Namespace Reference
Provides geometrical methods such as point inside rectangle.
Functions
bool isPointInsideRectangle (util::Point3 x, double x_min, double x_max, double y_min, double y_max)
Checks if point is inside a rectangle.
bool isPointInsideRectangle (util::Point3 x, util::Point3 x_lb, util::Point3 x_rt)
Checks if point is inside a rectangle.
bool isPointInsideAngledRectangle (util::Point3 x, double x_min, double x_max, double y_min, double y_max, double theta)
Checks if point is inside an angled rectangle.
bool isPointInsideCuboid (util::Point3 x, double x_min, double x_max, double y_min, double y_max, double z_min, double z_max)
Checks if point is inside a Cuboid.
bool isPointInsideCuboid (util::Point3 x, util::Point3 x_lbb, util::Point3 x_rtf)
Checks if point is inside a Cuboid.
double triangleArea (const util::Point3 &v1, const util::Point3 &v2, const util::Point3 &v3)
Computes the area of triangle.
Detailed Description
Provides geometrical methods such as point inside rectangle.
Function Documentation
isPointInsideAngledRectangle()
bool util::geometry::isPointInsideAngledRectangle (util::Point3 x, double x_min, double x_max, double y_min, double y_max, double theta)
Checks if point is inside an angled rectangle.
Parameters
x Point
x_min X coordinate of left-bottom corner point
x_max X coordinate of right-top corner point
y_min Y coordinate of left-bottom corner point
y_max Y coordinate of right-top corner point
theta Angle of orientation of rectangle from x-axis
Returns
bool True if point inside rectangle, else false
Referenced by loading::FLoading::FLoading(), and loading::ULoading::ULoading().
isPointInsideCuboid() [1/2]
bool util::geometry::isPointInsideCuboid (util::Point3 x, double x_min, double x_max, double y_min, double y_max, double z_min, double z_max)
Checks if point is inside a Cuboid.
Parameters
x Point
x_min X coordinate of left-bottom-back corner point
x_max X coordinate of right-top-front corner point
y_min Y coordinate of left-bottom-back corner point
y_max Y coordinate of right-top-front corner point
z_min Z coordinate of left-bottom-back corner point
z_max Z coordinate of right-top-front corner point
Returns
bool True if point inside
Referenced by loading::FLoading::FLoading(), isPointInsideCuboid(), and loading::ULoading::ULoading().
isPointInsideCuboid() [2/2]
bool util::geometry::isPointInsideCuboid (util::Point3 x, util::Point3 x_lbb, util::Point3 x_rtf)
Checks if point is inside a Cuboid.
Parameters
x Point
x_lbb Coordinate of left-bottom-back corner point
x_rtf Coordinate of right-top-front corner point
Returns
bool True if point inside
isPointInsideRectangle() [1/2]
bool util::geometry::isPointInsideRectangle (util::Point3 x, double x_min, double x_max, double y_min, double y_max)
Checks if point is inside a rectangle.
Parameters
x Point
x_min X coordinate of left-bottom corner point
x_max X coordinate of right-top corner point
y_min Y coordinate of left-bottom corner point
y_max Y coordinate of right-top corner point
Returns
bool True if point inside rectangle, else false
Referenced by model::FDModel::checkOutputCriteria(), tools::pp::Compute::decomposeSearchNodes(), loading::FLoading::FLoading(), tools::pp::Compute::getRectsAndNodesForCrackTip(), tools::pp::Compute::init(), tools::pp::Compute::listElemsAndNodesInDomain(), and loading::ULoading::ULoading().
isPointInsideRectangle() [2/2]
bool util::geometry::isPointInsideRectangle (util::Point3 x, util::Point3 x_lb, util::Point3 x_rt)
Checks if point is inside a rectangle.
Parameters
x Point
x_lb Coordinate of left-bottom corner point
x_rt Coordinate of right-top corner point
Returns
bool True if point inside rectangle, else false
triangleArea()
double util::geometry::triangleArea (const util::Point3 & v1, const util::Point3 & v2, const util::Point3 & v3)
Computes the area of triangle.
Parameters
v1 First vertex
v2 Second vertex
v3 Third vertex
Returns
area Triangle area