Nonlocalheatequation: solver Class Reference
solver Class Reference
Public Types
typedef util::Point3 point_3d
3d coordinate for representation of point
typedef std::vector< point_3d > plane_3d
3d plane using the 3d point representation Note that the plane is actually stored in a 1d fashion
typedef hpx::shared_future< partition_space > partition_fut
partitioning the 2d space into npx * npy small squares which constitute a partition of space
typedef std::vector< partition_fut > space_2d_fut
2d space data structure which consists of future of square partitions
typedef std::vector< partition_space_client > space_2d
2d space representation for temperature data
Public Member Functions
solver (long nt, long nlog, long nbalance, bool test, const std::string &filename="None")
constructor to allocate and initialize class variables
void param_file_input (const std::string &filename)
void compute_l2 (long time)
void compute_linf (long time)
void print_error (bool cmp)
void print_soln ()
print the solution for the user
void test_load_balance ()
void locality_subdomain_bfs (int node_id, int node_subdomain, std::vector< std::vector< int > > &locality_ids, int visited_subdomain[], int visited_node[], int work_realloc[], int total_subdomains[])
void redistribution_dfs (int parent_id, int node_id, std::vector< std::vector< int > > &locality_ids, std::set< int > adj_set[], int visited_subdomain[], int visited_node[], int work_realloc[], int node_subdomain[], int total_subdomains[])
std::vector< partition_space_client > load_balance (std::vector< partition_space_client > unbalanced_data)
void do_work ()
Compute the numerical solution on 'nx * ny' data points for each of 'npx * npy' partitions for 'nt' time steps.
Static Public Member Functions
static void log_csv_vtk (std::vector< partition_space > temp_data, plane_3d coord, long time, bool test)
static double influence_function (double distance)
static void add_neighbour_rectangle (long lx, long ly, long rx, long ry, space_2d &all_squares, space_2d &neighbour_squares)
static double w (long pos_x, long pos_y, long time)
static double boundary (long pos_x, long pos_y, const std::vector< partition_space > &all_squares)
static double boundary (long pos_x, long pos_y, double val)
static double distance (long cen_x, long cen_y, long pos_x, long pos_y)
static double len_1d_line (long len_x)
Function to compute length of 3rd side of a right angled triangle given hypotenuse and lenght of one side.
static double sum_local_test (long pos_x, long pos_y, long time)
static double sum_local (long pos_x, long pos_y, const std::vector< partition_space > &all_squares)
static space_2d_fut vector_get_data (const std::vector< partition_space_client > &neighbour_squares)
Function to retrieve the data from possibly remote partitions for vector of square sundomains.
static partition_space_client sum_local_partition (partition_space_client const &middle, const std::vector< partition_space_client > &neighbour_squares, long time, bool test)
Data Fields
space_2d S [2]
alternate for space between time steps, result of S[t%2] goes to S[(t+1)%2] at every timestep 't'
plane_3d P
vector containining 3d coordinates of the points in the plane
long nt
number of timesteps
long nlog
Number of time steps to log the results.
long nbalance
Number of time steps to run load balancing algorithm.
bool current
boolean variable to store index of current mesh which is already computed
bool next
boolean variable to store index of next mesh which is being computed
bool test
true if the analyitcal solution needs to be compared with the numerical solution
double error_l2
l2 norm
double error_linf
l infinity norm
std::vector< hpx::id_type > localities
std::vector of id's of various available localitites for computation
Detailed Description
class which contains the code to solve the 2d nonlocal equation in a distributed setup. The class contains functions to run the solver in a distributed setup with support for logging at regular intervals.
Constructor & Destructor Documentation
solver()
solver::solver (long nt, long nlog, long nbalance, bool test, const std::string & filename = "None") inline
constructor to allocate and initialize class variables
Internally calls get_loc() function
See also
partition_space_client
partition_space_server
partition_space
Parameters
nt number of timesteps to execute the sover
nlog number of iterations after which we want to log
nbalance number of time steps to run load balancing algorithm
test true if numerical solution needs to be tested against analytical solution
filename name of file to input the mesh from
Member Function Documentation
add_neighbour_rectangle()
static void solver::add_neighbour_rectangle (long lx, long ly, long rx, long ry, space_2d & all_squares, space_2d & neighbour_squares) inline static
function for inserting the rectangles which are just above, below and on the sides of the given partition into the unordered_map used to index the squares already inserted into the vector
Parameters
lx rectangle's lower left point's x coordinate
ly rectangle's lower left point's y coordinate
rx rectangle's upper right point's x coordinate
ry rectangle's upper right point's y coordinate
all_squares std::vector containing npx * npy squares from the partitioned grid
neighbour_squares std::vector containing the neighbour square subdomains from the current square
Referenced by do_work().
boundary() [1/2]
static double solver::boundary (long pos_x, long pos_y, const std::vector< partition_space > & all_squares) inline static
condition to enforce the boundary conditions for the divided partitions
Parameters
pos_x x coordinate of the point of computation
pos_y y coordinate of the point of computation
all_squares std::vector containing npx * npy squares from the partitioned grid
Returns
0 for points outside the mesh, else the value computed by the numerical solution for point (pos_x, pos_y)
Referenced by sum_local(), and sum_local_test().
boundary() [2/2]
static double solver::boundary (long pos_x, long pos_y, double val) inline static
condition to enforce the boundary conditions for the tests of analytical solution
Parameters
pos_x x coordinate of the point of computation
pos_y y coordinate of the point of computation
val expected value for analytical solution at the point (pos_x, pos_y)
Returns
0 for points outside the mesh, else the value computed by the analytical solution for point (pos_x, pos_y)
compute_l2()
void solver::compute_l2 (long time) inline
function to compute l2 norm of the solution
Parameters
time time at which we want to check the analytical solution against numerical solution
Referenced by print_error().
compute_linf()
void solver::compute_linf (long time) inline
function to compute l infinity norm of the solution
Parameters
time time at which we want to check the analytical solution against numerical solution
Referenced by print_error().
distance()
static double solver::distance (long cen_x, long cen_y, long pos_x, long pos_y) inline static
Function to find distance in 2d plane given 2 points coordinates
Parameters
cen_x x coordinate of the point of computation
cen_y y coordinate of the point of computation
pos_x x coordinate of the point that influences the temperature at (cen_x, cen_y)
pos_y y coordinate of the point that influences the temperature at (cen_x, cen_y)
Returns
distance of point (cen_x, cen_y) from point (pos_x, pos_y)
Referenced by sum_local(), and sum_local_test().
influence_function()
static double solver::influence_function (double distance) inline static
our influence function to weigh various points differently
Parameters
distance distance of the point from point of computation
Returns
returns the influence of the current point for point under computation
Referenced by sum_local(), and sum_local_test().
load_balance()
std::vector<partition_space_client> solver::load_balance (std::vector< partition_space_client > unbalanced_data) inline
Function to run the load balancing algorithm every nbalance time steps. Function reassigns localities to various square subdomains(if any) to have balanced computation across all the nodes in the distributed setup.
See also
locality_subdomain_bfs
redistribution_dfs
Parameters
unbalanced_data std::vector of client-side data structures for storing temperature data
Returns
std::vector of client-side data structures with some square subdomains possibly reassigned to different nodes
Referenced by do_work().
locality_subdomain_bfs()
void solver::locality_subdomain_bfs (int node_id, int node_subdomain, std::vector< std::vector< int > > & locality_ids, int visited_subdomain[], int visited_node[], int work_realloc[], int total_subdomains[]) inline
function for bfs for extending the domain corresponding to each of the nodes uniformly in all possible directions so that the change of shape in the region corresponding to a node does not change much
Parameters
node_id node id of the region whose boundary is being extended or contracted
node_subdomain a square subdomain's id in the region belonging to the current node
locality_ids locality id to which a particular square subdomain is attached
visited_subdomain data structure to keep a track of sudomains corresponding to current node
visited_node data structure to keep a track of visited nodes
work_realloc number of subdomains that need to be exchanged by various nodes
total_subdomains counter for each nodes denoting number of square subdomains for each of the nodes
Referenced by redistribution_dfs().
log_csv_vtk()
static void solver::log_csv_vtk (std::vector< partition_space > temp_data, plane_3d coord, long time, bool test) inline static
function to perform the logging in both csv and vtk format
Parameters
temp_data temperature data for 2d square subdomain
coord 3d coordinates for points in Point3 format
time time for which we are logging the results
test variable is true if we have to test the numerical solution against the analytical solution
Referenced by do_work().
param_file_input()
void solver::param_file_input (const std::string & filename) inline
Internally calls get_loc() function
Parameters
filename name of file to input the mesh from
Referenced by solver().
print_error()
void solver::print_error (bool cmp) inline
print error for testing
Parameters
cmp true if we want the print the analytical solution comparison against the numerical solution
redistribution_dfs()
void solver::redistribution_dfs (int parent_id, int node_id, std::vector< std::vector< int > > & locality_ids, std::set< int > adj_set[], int visited_subdomain[], int visited_node[], int work_realloc[], int node_subdomain[], int total_subdomains[]) inline
function for inserting the rectangles which are just above, below and on the sides of the given partition into the unordered_map used to index the squares already inserted into the vector
See also
locality_subdomain_bfs
Parameters
parent_id node id of the parent in the DFS
node_id node id of the region whose boundary is being extended or contracted
locality_ids locality id to which a particular square subdomain is attached
adj_set adjacency list for each of the nodes
visited_subdomain data structure to keep a track of sudomains corresponding to current node
visited_node data structure to keep a track of visited nodes
work_realloc number of subdomains that need to be exchanged by various nodes
node_subdomain std::vector containing a square subdomain's id in the region belonging to the various nodes
total_subdomains counter for each nodes denoting number of square subdomains for each of the nodes
Referenced by load_balance().
sum_local()
static double solver::sum_local (long pos_x, long pos_y, const std::vector< partition_space > & all_squares) inline static
Our operator to find sum of 'eps' radius circle in vicinity of point P(x,y) Represent circle as a series of horizaontal lines of thickness 'dh'
Parameters
pos_x x coordinate of the point whose numerical solution is to be computed
pos_y y coordinate of the point whose numerical solution is to be computed
all_squares std::vector containing npx * npy squares from the partitioned grid
Returns
temperature value at point (pos_x, pos_y) for numerical solution
Referenced by sum_local_partition().
sum_local_partition()
static partition_space_client solver::sum_local_partition (partition_space_client const & middle, const std::vector< partition_space_client > & neighbour_squares, long time, bool test) inline static
partition of nx * ny cells which will be processed by a single thread to enable full utilization of all cores across all nodes in the cluster
Parameters
middle x coordinate of the point whose numerical solution is to be computed
neighbour_squares std::vector containing the neighbour square subdomains from the current square
time time for which we are logging the results
test variable is true if we have to test the numerical solution against the analytical solution
Returns
client side data structure for temperature values for a square subdomain
sum_local_test()
static double solver::sum_local_test (long pos_x, long pos_y, long time) inline static
function adds the external source to the 2d nonlocal heat equation for testing correctness of numerical solution against the analytical solution
See also
sum_local
Parameters
pos_x x coordinate of the point whose numerical solution is to be computed
pos_y y coordinate of the point whose numerical solution is to be computed
time time at which we want the numerical solution
Returns
temperature value at point (pos_x, pos_y) for analytical solution
Referenced by sum_local_partition().
test_load_balance()
void solver::test_load_balance () inline
See also
load_balance function for checking the load balancing and visualizing the same using hpx::performance counters
w()
static double solver::w (long pos_x, long pos_y, long time) inline static
testing operator to verify correctness
Parameters
pos_x x coordinate of the point of computation
pos_y y coordinate of the point of computation
time time at which we want the analytical solution
Returns
analytical solution's expected value at point (pos_x, pos_y)
Referenced by compute_l2(), compute_linf(), log_csv_vtk(), print_error(), and sum_local_test().
The documentation for this class was generated from the following file:
/root/project/src/2d_nonlocal_distributed.cpp