Nonlocalheatequation: rw::writer::VtkWriter Class Reference
rw::writer::VtkWriter Class Reference
A vtk writer for simple point data and complex fem mesh data.
#include <writer.h>
Public Member Functions
VtkWriter (const std::string &filename, const std::string &compress_type="")
Constructor.
void close ()
Closes the file and store it to the hard disk.
Mesh data
void appendNodes (const std::vector< util::Point3 > *nodes, const std::vector< util::Point3 > *u=nullptr)
Writes the nodes to the file.
Point data
void appendPointData (const std::string &name, const std::vector< uint8_t > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< size_t > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< int > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< float > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< double > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< util::Point3 > *data)
Writes the vector point data to the file.
Cell data
void appendCellData (const std::string &name, const std::vector< float > *data)
Writes the float data associated to cells to the file.
Field data
void appendFieldData (const std::string &name, const double &data)
Writes the scalar field data to the file.
void appendFieldData (const std::string &name, const float &data)
Writes the scalar field data to the file.
void addTimeStep (const double &timestep)
Writes the time step to the file.
Private Attributes
vtkSmartPointer< vtkXMLUnstructuredGridWriter > d_writer_p
XML unstructured grid writer.
vtkSmartPointer< vtkUnstructuredGrid > d_grid_p
Unstructured grid.
std::string d_compressType
compression_type Specify the compressor (if any)
Detailed Description
A vtk writer for simple point data and complex fem mesh data.
Constructor & Destructor Documentation
VtkWriter()
rw::writer::VtkWriter::VtkWriter (const std::string & filename, const std::string & compress_type = "") explicit
Constructor.
Creates and opens .vtu file of name given by filename. The file remains open till the close() function is invoked.
Parameters
filename Name of file which will be created
compress_type Compression method (optional)
Member Function Documentation
addTimeStep()
void rw::writer::VtkWriter::addTimeStep (const double & timestep)
Writes the time step to the file.
Parameters
timestep Current time step of the simulation
Referenced by solver::log_csv_vtk().
appendCellData()
void rw::writer::VtkWriter::appendCellData (const std::string & name, const std::vector< float > * data)
Writes the float data associated to cells to the file.
Parameters
name Name of the data
data Vector containing the data
appendFieldData() [1/2]
void rw::writer::VtkWriter::appendFieldData (const std::string & name, const double & data)
Writes the scalar field data to the file.
Parameters
name Name of the data
data Value
appendFieldData() [2/2]
void rw::writer::VtkWriter::appendFieldData (const std::string & name, const float & data)
Writes the scalar field data to the file.
Parameters
name Name of the data
data Value
appendNodes()
void rw::writer::VtkWriter::appendNodes (const std::vector< util::Point3 > * nodes, const std::vector< util::Point3 > * u = nullptr)
Writes the nodes to the file.
Parameters
nodes Reference positions of the nodes
u Nodal displacements
Referenced by solver::log_csv_vtk().
appendPointData() [1/6]
void rw::writer::VtkWriter::appendPointData (const std::string & name, const std::vector< double > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [2/6]
void rw::writer::VtkWriter::appendPointData (const std::string & name, const std::vector< float > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [3/6]
void rw::writer::VtkWriter::appendPointData (const std::string & name, const std::vector< int > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [4/6]
void rw::writer::VtkWriter::appendPointData (const std::string & name, const std::vector< size_t > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [5/6]
void rw::writer::VtkWriter::appendPointData (const std::string & name, const std::vector< uint8_t > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
Referenced by solver::log_csv_vtk().
appendPointData() [6/6]
void rw::writer::VtkWriter::appendPointData (const std::string & name, const std::vector< util::Point3 > * data)
Writes the vector point data to the file.
Parameters
name Name of the data
data Vector containing the data
The documentation for this class was generated from the following files:
/root/project/include/writer.h
/root/project/include/writer.cpp